#!/usr/bin/env python3
"""coverage.py の JSON レポートを GitHub PR コメント用の Markdown に整形する。

副作用はなく、引数で受け取った coverage.json を読み、整形した Markdown を
標準出力へ書き出すだけ。PR への投稿は coverage-comment.sh（gh CLI）が担当する
（整形と投稿で責任を分離している）。

使い方:
    python coverage_md.py <coverage.json のパス>

任意の環境変数（フッターのリンク生成に使用。無ければその部分を省略する）:
    GITHUB_SERVER_URL, GITHUB_REPOSITORY, GITHUB_RUN_ID,
    GITHUB_RUN_NUMBER, COMMIT_SHA
"""

from __future__ import annotations

import json
import os
import sys

# coverage-comment.sh の検索キーと一致させること（変更時は両方直す）。
MARKER = "<!-- coverage-report -->"

# カバレッジ率に応じた信号機の絵文字のしきい値（%）。
GREEN_THRESHOLD = 80.0
YELLOW_THRESHOLD = 50.0


def status_emoji(percent: float) -> str:
    """カバレッジ率に応じた信号機の絵文字を返す。"""
    if percent >= GREEN_THRESHOLD:
        return "🟢"
    if percent >= YELLOW_THRESHOLD:
        return "🟡"
    return "🔴"


def percentage(covered: int, total: int) -> float:
    """covered / total を百分率で返す。total が 0 のときは 100% 扱い。"""
    return 100.0 * covered / total if total else 100.0


def summary_row(category: str, covered: int, total: int) -> str:
    """全体サマリ表の 1 行を組み立てる。"""
    pct = percentage(covered, total)
    return f"| {status_emoji(pct)} | {category} | {pct:.2f}% | {covered} / {total} |"


def coverage_cell(covered: int, total: int) -> str:
    """ファイル別表のセル（絵文字 + 率）。集計対象が無ければダッシュ。"""
    if total == 0:
        return "—"
    pct = percentage(covered, total)
    return f"{status_emoji(pct)} {pct:.2f}%"


def build_markdown(data: dict) -> str:
    totals = data["totals"]
    files = data.get("files", {})

    lines = [
        MARKER,
        "## 📊 Coverage Report",
        "",
        "| Status | Category | Percentage | Covered / Total |",
        "| :---: | :--- | ---: | ---: |",
        summary_row("Lines", totals["covered_lines"], totals["num_statements"]),
    ]
    # Branch coverage は branch=true のときだけ意味を持つ。
    if totals.get("num_branches", 0) > 0:
        lines.append(
            summary_row("Branches", totals["covered_branches"], totals["num_branches"])
        )

    # ファイル別の内訳（折りたたみ）。
    if files:
        lines += [
            "",
            "<details>",
            "<summary>📁 File Coverage</summary>",
            "",
            "| File | Lines | Branches |",
            "| :--- | ---: | ---: |",
        ]
        for path, info in sorted(files.items()):
            s = info["summary"]
            cell_lines = coverage_cell(s["covered_lines"], s["num_statements"])
            cell_branches = coverage_cell(
                s.get("covered_branches", 0), s.get("num_branches", 0)
            )
            lines.append(f"| `{path}` | {cell_lines} | {cell_branches} |")
        lines += ["", "</details>"]

    # フッター（実行へのリンク）。環境変数が揃っているときだけ付ける。
    server = os.environ.get("GITHUB_SERVER_URL")
    repo = os.environ.get("GITHUB_REPOSITORY")
    run_id = os.environ.get("GITHUB_RUN_ID")
    run_number = os.environ.get("GITHUB_RUN_NUMBER")
    sha = os.environ.get("COMMIT_SHA", "")
    if server and repo and run_id:
        run_url = f"{server}/{repo}/actions/runs/{run_id}"
        label = f"#{run_number}" if run_number else "run"
        footer = f"_Generated by workflow [{label}]({run_url})_"
        if sha:
            footer += f" · commit `{sha[:7]}`"
        lines += ["", footer]

    return "\n".join(lines) + "\n"


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: coverage_md.py <coverage.json>", file=sys.stderr)
        return 2

    with open(sys.argv[1], encoding="utf-8") as f:
        data = json.load(f)

    sys.stdout.write(build_markdown(data))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
